// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package entity

import (
	"time"
)

type LocaldbUser struct {
	ID        uint64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
