// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package controller

// Message defines model for Message.
type Message struct {
	Message string `json:"message"`
}
